name: Rodar script automaticamente

on:
  schedule:
    - cron: '0 * * * *'   # Todo início de hora
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Criar arquivo de credenciais do Google
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > temp.json
          cat temp.json | jq '.' > credentials.json

      - name: Executar script Python
        run: python Base_Visitas_Nonata.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          PATH_CREDENTIALS: './credentials.json'